### ISSUE TITLE
Make the dependencies looser

### ISSUE THREAD

**Issue by felipecrs** [vscode-restructuredtext/snooty-parser#12]
It would be very cool if you could make the dependencies of this project (such as requests and docutils) more looser, so I could the snooty-lexstudio to my dev-dependencies with less hassle.

For example, you currently accept: requests >=2.24.0,<2.25.0. I believe you could safely accept >=2.24.0,<3.0.0 for example.

```sh-session
$ poetry add --dev snooty-lextudio
Using version ^1.8.6-alpha.0 for snooty-lextudio

Updating dependencies
Resolving dependencies... (0.2s)

  SolverProblemError

  Because no versions of snooty-lextudio match >1.8.6-alpha.0,<2.0.0
   and snooty-lextudio (1.8.6.dev0) depends on requests (>=2.24.0,<2.25.0), snooty-lextudio (>=1.8.6-alpha.0,<2.0.0) requires requests (>=2.24.0,<2.25.0).
  So, because river-cicd depends on both requests (^2.25.1) and snooty-lextudio (^1.8.6-alpha.0), version solving failed.
```

**Comment by lextm** [comment]
Should have been resolved in recent releases, as the changes from upstream relaxed the constraints.
