### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'uri' when typing text in vscode

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/snooty-parser#17]
```
ERROR:pyls_jsonrpc.endpoint:Failed to handle request 23
Traceback (most recent call last):
  File "[deleted]/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "[deleted]/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "[deleted]/.tox/py3/lib/python3.8/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "[deleted]/.tox/py3/lib/python3.8/site-packages/snooty/language_server.py", line 450, in m_text_document__completion
    return self.completions(textDocument.uri, position)
AttributeError: 'dict' object has no attribute 'uri'
[Error - 7:48:39 AM] Request textDocument/completion failed.
  Message: AttributeError: 'dict' object has no attribute 'uri'
  Code: -32602 
[object Object]
```

**Comment by oharboe** [comment]
snooty 1.8.7.dev0
Python 3.8.5

from our tox.ini file:

    alabaster == 0.7.12
    argcomplete == 1.12.2
    astroid == 2.4.2
    attrdict == 2.0.1
    attrs == 20.3.0
    Babel == 2.9.0
    blockdiag == 2.0.1
    cachetools == 4.2.1
    cairocffi == 1.2.0
    CairoSVG == 2.5.1
    certifi == 2020.12.5
    cffi == 1.14.4
    chardet == 3.0.4
    cryptography == 3.3.1
    cssselect2 == 0.4.1
    decorator == 4.4.2
    defusedxml == 0.6.0
    distro == 1.5.0
    dnspython == 1.16.0
    doc8 == 0.8.1
    docopt == 0.6.2
    docutils == 0.16
    docxbuilder == 1.2.0
    fett == 0.3.2
    funcparserlib == 0.3.6
    future == 0.18.2
    gitdb == 4.0.5
    GitPython == 3.1.12
    google-api-core == 1.25.1
    google-auth == 1.24.0
    google-cloud-core == 1.5.0
    google-cloud-datastore == 2.1.0
    googleapis-common-protos == 1.52.0
    grpcio == 1.35.0
    httplib2 == 0.18.1
    idna == 2.10
    imagesize == 1.2.0
    iniconfig == 1.1.1
    isort == 5.7.0
    jeepney == 0.6.0
    Jinja2 == 2.11.3
    junitparser == 2.0.0
    keyring == 22.0.1
    launchpadlib == 1.10.13
    lazr.restfulclient == 0.14.3
    lazr.uri == 1.0.5
    lazy-object-proxy == 1.4.3
    libcst == 0.3.16
    MarkupSafe == 1.1.1
    mccabe == 0.6.1
    mypy-extensions == 0.4.3
    networkx == 2.5
    nwdiag == 2.0.0
    oauth == 1.0.1
    oauthlib == 3.1.0
    packaging == 20.9
    pathtools == 0.1.2
    pbr == 5.5.1
    Pillow == 8.1.0
    pluggy == 0.13.1
    proto-plus == 1.13.0
    protobuf == 3.14.0
    py == 1.10.0
    pyasn1 == 0.4.8
    pyasn1-modules == 0.2.8
    pycparser == 2.20
    Pygments == 2.7.4
    pylint == 2.6.0
    pymongo == 3.11.2
    pyparsing == 2.4.7
    pytest == 6.2.2
    pytest-mock == 3.5.1
    python-jsonrpc-server == 0.3.4
    pytz == 2021.1
    PyYAML == 5.3.1
    reportlab == 3.5.59
    requests == 2.24.0
    restructuredtext-lint == 1.3.2
    rsa == 4.7
    rstcheck == 3.3.1
    SecretStorage == 3.3.0
    six == 1.15.0
    smmap == 3.0.5
    snooty-lextudio == 1.8.7.dev0
    snowballstemmer == 2.1.0
    Sphinx == 3.4.3
    sphinx-rtd-theme == 0.5.1
    sphinxcontrib-applehelp == 1.0.2
    sphinxcontrib-blockdiag == 2.0.0
    sphinxcontrib-devhelp == 1.0.2
    sphinxcontrib-htmlhelp == 1.0.3
    sphinxcontrib-jsmath == 1.0.1
    sphinxcontrib-nwdiag == 2.0.0
    sphinxcontrib-plantuml == 0.19
    sphinxcontrib-programoutput == 0.16
    sphinxcontrib-qthelp == 1.0.3
    sphinxcontrib-runcmd == 0.2.0
    sphinxcontrib-serializinghtml == 1.1.4
    sphinxcontrib-tikz == 0.4.11
    sphinxcontrib-wavedrom == 2.1.1
    sphinxcontrib.datatemplates == 0.7.2
    stevedore == 3.3.0
    svgwrite == 1.4.1
    termcolor == 1.1.0
    testresources == 2.0.1
    tinycss2 == 1.1.0
    toml == 0.10.2
    typing-extensions == 3.7.4.3
    typing-inspect == 0.6.0
    ujson == 1.35
    urllib3 == 1.25.11
    wadllib == 1.3.5
    watchdog == 0.10.4
    wavedrom == 2.0.3.post2
    webcolors == 1.11.1
    webencodings == 0.5.1
    wrapt == 1.12.1
    xcffib == 0.11.1
    # FIXME we can't upgrade yapf unless we reformat python scripts
    yapf == 0.23.0

**Comment by lextm** [comment]
Duplicate to #18
