### ISSUE TITLE
Error loading the snooty parser

### ISSUE THREAD

**Issue by macshaggy** [vscode-restructuredtext/snooty-parser#5]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: v132.0
- [ ] Visual Studio Code version: 1.52.0
- [ ] Operating System version: Windows 10 Pro Build 20H2
- [ ] Python version: 3.9.0
- [ ] sphinx version: 3.3.1
- [ ] A sample of conf.py or its important fragments: none to show

**Expected behavior**
Snooty will load and be ready.

**Actual behavior**
Couldn't start client Snooty Language Client

FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\c%3A\\Users\\jason\\source\\test-project'

Cannot lint c:\Users\jason\source\temp\test.rst. The executable '"C:\Users\jason\AppData\Local\Programs\Python\Python39\Scripts\rstcheck.exe"' was not found. Use the 'restructuredtext.linter.executablePath' setting to configure the location of the executable

**Detailed Steps to reproduce the problem**
I installed everything per the instructions. And then added the path to the linter and I get this error.

Also, this doesn't work in virtual environments.

**Comment by lextm** [comment]
It seems to be easy to fix, so you can do the following on your machine to use the latest Snooty.
```
pip uninstall snooty
pip install snooty-lextudio --upgrade
```
Verify that 1.8.3 release is installed, and then it should work on Windows now.

**Comment by macshaggy** [comment]
That works thanks man!
