### ISSUE TITLE
Back port to python 3.6

### ISSUE THREAD

**Issue by jamesharris-garmin** [vscode-restructuredtext/snooty-parser#7]
Many existing ubuntu users are using 18.04 LTS and transitioning away will be slow. 3.6 is the version of python that ships with ubuntu so it would be extremely helpful if this package were backward compatible or tested with python 3.6.  Without this the vscode plugin cannot install the language parser on older systems.

**Comment by lextm** [comment]
Pull requests are welcome, as I don't think I know enough to work on this item.

**Comment by jamesharris-garmin** [comment]
I'm surprised that this project doesn't support tox. (which would make running its test suite much easier. But [this line](https://github.com/vscode-restructuredtext/snooty-parser/blob/13b427ce5b12a850c90d9e4b8a21b7c7fc777f21/pyproject.toml#L14) could be changed to include python 3.6 as follows:

```toml
requires-python = ">=3.6,<4"
```
which would support python 3.6 through 3.9

the next step would be to provide a testing environment that could invoke the test suite in those environments and start cranking through errors.

a free service like circle-ci, travis-ci or similar would allow you to validate pull requests and changes against the project.

I'm a little surprised the upstream fork doesn't have this setup to begin with.

**Comment by zachlewis** [comment]
Alternatively, would it be possible to select a custom, non-system python interpreter?

**Comment by lextm** [comment]
3.6 will reach end of life in just a few weeks, so time to close this.
